# Generated by Django 3.2.12 on 2022-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220429_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Местоположение'),
        ),
    ]
