# Generated by Django 3.2.12 on 2022-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220429_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Фото'),
        ),
    ]
