# Generated by Django 3.2.12 on 2022-05-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_updating',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления записи'),
        ),
    ]
