# Generated by Django 3.2.12 on 2022-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_location'),
        ('auth_', '0003_auto_20220429_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
