# Generated by Django 3.2.12 on 2022-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20220429_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='photo',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', max_length=150, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
