# Generated by Django 3.2.12 on 2022-04-30 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0006_auto_20220429_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место обучения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
