# Generated by Django 3.2.12 on 2022-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0007_auto_20220430_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.IntegerField(default=2, verbose_name='Курс'),
        ),
    ]
