# Generated by Django 3.2.12 on 2022-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0008_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Курс'),
        ),
    ]
